#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf constant/polyMesh/sets

runApplication blockMesh
runApplication setSet -batch makeCellSets.setSet

rm -f constant/polyMesh/sets/*_old

runApplication setsToZones -noFlipMap
runApplication splitMeshRegions -cellZones -overwrite

echo "remove fluid fields from solid regions (important for post-processing)"
rm -f 0*/heatSink/{mut,alphat,epsilon,k,p_rgh,p,U}

echo "remove solid fields from fluid regions (important for post-processing)"
rm -f 0*/Air/{cp,K,rho}

for i in heatSink Air
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done


##-- Run on single processor
#runApplication chtMultiRegionSimpleFoam
#
## Decompose
#for i in Air
#do
#   decomposePar -region $i > log.decomposePar.$i 2>&1
#done
#
## Run
#runParallel chtMultiRegionSimpleFoam 6
#
## Reconstruct
#for i in Air
#do
#   reconstructPar -region $i > log.reconstructPar.$i 2>&1
#done
#
#
echo
echo "creating files for paraview post-processing"
echo
for i in Air heatSink
do
   paraFoam -touch -region $i
done

## ----------------------------------------------------------------- end-of-file
